### ISSUE TITLE
ragdoll physics issue 

### ISSUE THREAD

**Issue by shohan4556** [StasClick/ragdoll_helper#1]
Hi, it creates ragdoll nicely but in playmode the humanoid object acting crazy

**Comment by StasClick** [comment]
Hi. I tried to reproduce it on my models and it looks smooth. Could you send me your model? Or better to send a prepared project because there could be something with ragdoll setup. With regards,Stas08.12.2019, 14:42, "Shohanur Rahaman" <notifications@github.com>:Hi, it creates ragdoll nicely but in playmode the humanoid object acting crazy

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С уважением Станислав Березовиков.

**Comment by shohan4556** [comment]
> Hi. I tried to reproduce it on my models and it looks smooth. Could you send me your model? Or better to send a prepared project because there could be something with ragdoll setup. With regards,Stas08.12.2019, 14:42, "Shohanur Rahaman" <notifications@github.com>:Hi, it creates ragdoll nicely but in playmode the humanoid object acting crazy —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. -- С уважением Станислав Березовиков.

I have tried this zombie model https://www.reddit.com/r/gamedev/comments/7pla8z/free_lowpoly_animated_zombie/

**Comment by StasClick** [comment]
Hi. I looked at your model.There a problem with sphere collider on the head and due to different scaling, ragdoll helper is not able to fix it (it a ragdoll helper bug).Solutions:- do not use non 1 scaling.- adjust head collider manually. Also, I can say using scaling different than 1 is not recommended with ragdoll. Read unity suggestions https://docs.unity3d.com/Manual/RagdollStability.html With regards,Stas12.12.2019, 07:31, "Shohanur Rahaman" <notifications@github.com>:
Hi. I tried to reproduce it on my models and it looks smooth. Could you send me your model? Or better to send a prepared project because there could be something with ragdoll setup. With regards,Stas08.12.2019, 14:42, "Shohanur Rahaman" notifications@github.com:Hi, it creates ragdoll nicely but in playmode the humanoid object acting crazy —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. -- С уважением Станислав Березовиков.

I have tried this zombie model https://www.reddit.com/r/gamedev/comments/7pla8z/free_lowpoly_animated_zombie/

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С уважением Станислав Березовиков.

**Comment by shohan4556** [comment]
thanks for your support.
